name: Node.js CI

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3.0.0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: NODE_ENV=production NODE_OPTIONS=--max-old-space-size=464 pnpm run build
    - run: ls built/meta.json

