name: Node.js CI

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    services:
      postgres:
        image: postgres:13
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:6
        ports:
          - 56312:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get install -y ffmpeg
    - run: yarn install
    - run: git diff --exit-code yarn.lock
    - run: yarn build
    - run: cp .github/misskey/test.yml .config/
    - run: yarn test
